# Generated by Django 5.1.2 on 2024-10-27 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testroom',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
