# Generated by Django 5.1.2 on 2024-10-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testroom_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testroom',
            name='max_point',
            field=models.IntegerField(default=100),
        ),
    ]
