# Generated by Django 5.1.2 on 2024-10-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testroom_max_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_point', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentmodel')),
                ('testroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testroom')),
            ],
        ),
    ]
