# Generated by Django 5.1.2 on 2024-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subjectmodel_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='teacher',
            field=models.CharField(max_length=50),
        ),
    ]
