# Generated by Django 5.1.2 on 2024-10-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tacher',
            new_name='Teacher',
        ),
    ]
